#############################################################
#															#
#				nuri-proxy(nproxy) Makefile					#
#										@author: hyun5		#
#############################################################

all:
	( cd _NPROXY_; make all; cd .. )
	( cd _NTRAP_; make all; cd .. )
clean:
	( cd _NPROXY_; make clean; cd ..)
	( cd _NTRAP_; make clean; cd ..)
